name: Build NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: christopherpow/nes-test-roms
        path: ./nes-test-roms

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore packages
      run: |
           dotnet restore

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Build
      run: |
           dotnet build --configuration Debug --no-restore /p:DefineConstants="CI_CONTEXT"

    - name: Unit testing
      run: |
           coverlet NesCs.UnitTests/bin/Debug/net7.0/NesCs.UnitTests.dll --target "dotnet" --targetargs "test NesCs.UnitTests/NesCs.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output nescs.coverage.xml

    - name: Integration testing
      run: |
           coverlet NesCs.Roms.IntegrationTests/bin/Debug/net7.0/NesCs.Roms.IntegrationTests.dll --target "dotnet" --targetargs "test NesCs.Roms.IntegrationTests/NesCs.Roms.IntegrationTests.csproj --no-build --verbosity quiet" --format OpenCover --output nescs.roms.coverage.xml

    - name: Upload coverage to CodeCov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./*.coverage.xml
